"""add catch group

Revision ID: 0a40bf271d0c
Revises: 1802f4a16a81
Create Date: 2024-06-25 00:11:40.458010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a40bf271d0c"
down_revision: Union[str, None] = "1802f4a16a81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catch_catch_group",
        sa.Column("weight", sa.Float(), server_default="0", nullable=False),
        sa.Column("time_limit_rule", sa.String(), nullable=False),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("data_id"),
    )
    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.add_column(sa.Column("catch_group", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_catch_award_catch_group"), ["catch_group"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_catch_award_catch_group_catch_catch_group_data_id",
            "catch_catch_group",
            ["catch_group"],
            ["data_id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_catch_award_catch_group_catch_catch_group_data_id", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_catch_award_catch_group"))
        batch_op.drop_column("catch_group")

    op.drop_table("catch_catch_group")
    # ### end Alembic commands ###
