"""CDKEY UPDATE

Revision ID: b6acc95e6ac3
Revises: 20240831T063503Z
Create Date: 2024-09-16 12:26:35.002752

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6acc95e6ac3"
down_revision: Union[str, None] = "20240831T063503Z"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catch_cdk",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("data_id"),
    )
    op.create_table(
        "catch_cdk_award",
        sa.Column("cdk_id", sa.Integer(), nullable=True),
        sa.Column("aid", sa.Integer(), nullable=True),
        sa.Column("sid", sa.Integer(), nullable=True),
        sa.Column("chips", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["aid"], ["catch_award.data_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cdk_id"], ["catch_cdk.data_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sid"], ["catch_skin.data_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("data_id"),
    )
    op.create_table(
        "catch_cdk_usage",
        sa.Column("cdk_id", sa.Integer(), nullable=True),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["cdk_id"], ["catch_cdk.data_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uid"], ["catch_user_data.data_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("data_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catch_cdk_usage")
    op.drop_table("catch_cdk_award")
    op.drop_table("catch_cdk")
    # ### end Alembic commands ###
