"""ADD SKIN FIELDS

Revision ID: 5e6a95860415
Revises: fcf080a5e878
Create Date: 2024-11-04 10:43:25.623364

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e6a95860415"
down_revision: Union[str, None] = "fcf080a5e878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("biscuit", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.add_column(
            sa.Column("level", sa.Integer(), server_default="0", nullable=False)
        )

    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "buy_skin_box_last_time", sa.Float(), server_default="0", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.drop_column("buy_skin_box_last_time")

    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.drop_column("level")
        batch_op.drop_column("biscuit")

    # ### end Alembic commands ###
