"""pool update final

Revision ID: 20240811T080200Z
Revises: 20240809T142155Z
Create Date: 2024-08-11 16:02:04.684534

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240811T080200Z"
down_revision: Union[str, None] = "20240809T142155Z"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catch_pack_award_relationship",
        sa.Column("pack", sa.Integer(), nullable=False),
        sa.Column("aid", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["aid"], ["catch_award.data_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("data_id"),
    )
    with op.batch_alter_table("catch_pack_award_relationship", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_pack_award_relationship_aid"), ["aid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_catch_pack_award_relationship_pack"), ["pack"], unique=False
        )

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("main_pack_id", sa.Integer(), server_default="1", nullable=True)
        )

    op.execute("UPDATE catch_award SET main_pack_id=pack_id")

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_index("ix_catch_award_pack_id")
        batch_op.create_index(
            batch_op.f("ix_catch_award_main_pack_id"), ["main_pack_id"], unique=False
        )
        batch_op.drop_column("pack_id")

    with op.batch_alter_table("catch_up_pool_inventory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_up_pool_inventory_pool_id"), ["pool_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_catch_up_pool_inventory_uid"), ["uid"], unique=False
        )

    with op.batch_alter_table("catch_up_pool_relationship", schema=None) as batch_op:
        batch_op.drop_index("catch_up_pool_rel_index")
        batch_op.create_index(
            batch_op.f("ix_catch_up_pool_relationship_pool_id"),
            ["pool_id"],
            unique=False,
        )

    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("own_packs", sa.String(), server_default="1", nullable=False)
        )
        batch_op.drop_column("bought_pack_count")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "bought_pack_count",
                sa.INTEGER(),
                server_default=sa.text("'1'"),
                nullable=False,
            )
        )
        batch_op.drop_column("own_packs")

    with op.batch_alter_table("catch_up_pool_relationship", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_up_pool_relationship_pool_id"))
        batch_op.create_index("catch_up_pool_rel_index", ["aid", "pool_id"], unique=1)

    with op.batch_alter_table("catch_up_pool_inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_up_pool_inventory_uid"))
        batch_op.drop_index(batch_op.f("ix_catch_up_pool_inventory_pool_id"))

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pack_id", sa.INTEGER(), server_default=sa.text("'1'"), nullable=True
            )
        )
        batch_op.drop_index(batch_op.f("ix_catch_award_main_pack_id"))
        batch_op.create_index("ix_catch_award_pack_id", ["pack_id"], unique=False)
        batch_op.drop_column("main_pack_id")

    with op.batch_alter_table("catch_pack_award_relationship", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_pack_award_relationship_pack"))
        batch_op.drop_index(batch_op.f("ix_catch_pack_award_relationship_aid"))

    op.drop_table("catch_pack_award_relationship")
    # ### end Alembic commands ###
