"""pool update 2

Revision ID: 20240809T073627Z
Revises: 20240809T054608Z
Create Date: 2024-08-09 15:36:31.058982

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240809T073627Z"
down_revision: Union[str, None] = "20240809T054608Z"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "bought_pack_count", sa.Integer(), server_default="1", nullable=False
            )
        )
        batch_op.add_column(sa.Column("using_up_pool", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "using_pack",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            existing_server_default="1",
        )
        batch_op.create_foreign_key(
            "fk_user_using_pool",
            "catch_up_pool",
            ["using_up_pool"],
            ["data_id"],
            ondelete="SET NULL",
        )
        batch_op.drop_column("own_packs")

    op.execute(
        """
        UPDATE catch_user_data
        SET using_pack = 1
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "own_packs",
                sa.VARCHAR(),
                server_default=sa.text("('')"),
                nullable=False,
            )
        )
        batch_op.drop_constraint("fk_user_using_pool", type_="foreignkey")
        batch_op.alter_column(
            "using_pack",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
            existing_server_default="('')",
        )
        batch_op.drop_column("using_up_pool")
        batch_op.drop_column("bought_pack_count")

    # ### end Alembic commands ###
