"""pool update

Revision ID: 20240809T054608Z
Revises: 20240807T074135Z
Create Date: 2024-08-09 13:46:11.478068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240809T054608Z"
down_revision: Union[str, None] = "20240807T074135Z"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catch_up_pool",
        sa.Column("belong_pack", sa.Integer(), nullable=False),
        sa.Column("display", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("data_id"),
    )
    with op.batch_alter_table("catch_up_pool", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_up_pool_name"), ["name"], unique=False
        )

    op.create_table(
        "catch_up_pool_relationship",
        sa.Column("pool_id", sa.Integer(), nullable=True),
        sa.Column("aid", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["aid"], ["catch_award.data_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pool_id"], ["catch_up_pool.data_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("data_id"),
    )
    with op.batch_alter_table("catch_up_pool_relationship", schema=None) as batch_op:
        batch_op.create_index(
            "catch_up_pool_rel_index", ["aid", "pool_id"], unique=True
        )

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("pack_id", sa.Integer(), server_default="1", nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_catch_award_pack_id"), ["pack_id"], unique=False
        )

    op.execute(
        """
        UPDATE catch_award
        SET pack_id = -1
        WHERE is_special_get_only = 1
        """
    )

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_column("is_special_get_only")
        batch_op.drop_column("belong_pack")

    with op.batch_alter_table("catch_global", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("opened_pack", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_global", schema=None) as batch_op:
        batch_op.drop_column("opened_pack")

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "belong_pack",
                sa.VARCHAR(),
                server_default=sa.text("('')"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_special_get_only",
                sa.BOOLEAN(),
                server_default=sa.text("'0'"),
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_catch_award_pack_id"))
        batch_op.drop_column("pack_id")

    with op.batch_alter_table("catch_up_pool_relationship", schema=None) as batch_op:
        batch_op.drop_index("catch_up_pool_rel_index")

    op.drop_table("catch_up_pool_relationship")
    with op.batch_alter_table("catch_up_pool", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_up_pool_name"))

    op.drop_table("catch_up_pool")
    # ### end Alembic commands ###
