"""ITEM UPGRADE 2

Revision ID: 99b739f3cd9a
Revises: d47fb98d7383
Create Date: 2024-10-10 23:20:44.993299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99b739f3cd9a"
down_revision: Union[str, None] = "d47fb98d7383"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_item_inventory", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("stats", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_item_inventory", schema=None) as batch_op:
        batch_op.drop_column("stats")

    # ### end Alembic commands ###
