"""ADD BISCUIT

Revision ID: 38e7597b65a9
Revises: 99b739f3cd9a
Create Date: 2024-10-22 09:44:57.307747

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38e7597b65a9"
down_revision: Union[str, None] = "99b739f3cd9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.alter_column("award_id", new_column_name="aid")

    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("biscuit", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.alter_column("using_pack", new_column_name="using_pid")
        batch_op.alter_column("feature_flag", new_column_name="flags")
        batch_op.alter_column(
            "pick_count_last_calculated", new_column_name="slot_last_time"
        )
        batch_op.alter_column(
            "last_sleep_early_time", new_column_name="sleep_last_time"
        )
        batch_op.alter_column("sign_in_count", new_column_name="sign_count")
        batch_op.alter_column("last_sign_in_time", new_column_name="sign_last_time")
        batch_op.alter_column("sleep_early_count", new_column_name="sleep_count")
        batch_op.alter_column("pick_count_remain", new_column_name="slot_empty")
        batch_op.drop_column("pick_time_delta")
        batch_op.alter_column("pick_max_cache", new_column_name="slot_count")
        batch_op.alter_column("money", new_column_name="chips")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pick_time_delta", sa.FLOAT(), nullable=False, server_default="0.0"
            )
        )
        batch_op.drop_column("biscuit")

        batch_op.alter_column("using_pid", new_column_name="using_pack")
        batch_op.alter_column("flags", new_column_name="feature_flag")
        batch_op.alter_column(
            "slot_last_time", new_column_name="pick_count_last_calculated"
        )
        batch_op.alter_column(
            "sleep_last_time", new_column_name="last_sleep_early_time"
        )
        batch_op.alter_column("sign_count", new_column_name="sign_in_count")
        batch_op.alter_column("sign_last_time", new_column_name="last_sign_in_time")
        batch_op.alter_column("sleep_count", new_column_name="sleep_early_count")
        batch_op.alter_column("slot_empty", new_column_name="pick_count_remain")
        batch_op.alter_column("slot_count", new_column_name="pick_max_cache")
        batch_op.alter_column("chips", new_column_name="money")

    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.alter_column("aid", new_column_name="award_id")

    # ### end Alembic commands ###
