"""clear unmodified

Revision ID: 20240711T060459Z
Revises: 20240711T052226Z
Create Date: 2024-07-11 14:05:03.066417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20240711T060459Z"
down_revision: Union[str, None] = "20240711T052226Z"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_catch_skin_award",
            "catch_award",
            ["award_id"],
            ["data_id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("catch_skin_inventory", schema=None) as batch_op:
        batch_op.alter_column(
            "selected",
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default="0",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin_inventory", schema=None) as batch_op:
        batch_op.alter_column(
            "selected",
            existing_type=sa.INTEGER(),
            nullable=False,
            existing_server_default="0",
        )

    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.drop_constraint("fk_catch_skin_award", type_="foreignkey")

    # ### end Alembic commands ###
