"""Add logic

Revision ID: 440565df3bc4
Revises: 5e6a95860415
Create Date: 2024-11-25 14:53:01.018361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "440565df3bc4"
down_revision: Union[str, None] = "5e6a95860415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("can_be_pulled", sa.Integer(), server_default="1", nullable=False)
        )
        batch_op.add_column(
            sa.Column("can_be_bought", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.drop_column("can_be_bought")
        batch_op.drop_column("can_be_pulled")

    # ### end Alembic commands ###
