"""REMOVE DB IMAGE

Revision ID: fcf080a5e878
Revises: 154c643bb1fe
Create Date: 2024-10-24 00:04:01.001144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf080a5e878'
down_revision: Union[str, None] = '154c643bb1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('catch_skin', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_skin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
