"""pack change

Revision ID: 20240807T074135Z
Revises: 20240807T064740Z
Create Date: 2024-08-07 15:41:39.178126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240807T074135Z'
down_revision: Union[str, None] = '20240807T064740Z'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('own_packs', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('using_pack', sa.String(), server_default='', nullable=False))
        batch_op.drop_column('using_packs')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('using_packs', sa.VARCHAR(), server_default=sa.text("('')"), nullable=False))
        batch_op.drop_column('using_pack')
        batch_op.drop_column('own_packs')

    # ### end Alembic commands ###
