"""add recipe history index

Revision ID: 20240713T094332Z
Revises: 20240713T091516Z
Create Date: 2024-07-13 17:43:35.249135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20240713T094332Z'
down_revision: Union[str, None] = '20240713T091516Z'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_recipe_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catch_recipe_history_recipe'), ['recipe'], unique=False)
        batch_op.create_index(batch_op.f('ix_catch_recipe_history_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_recipe_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catch_recipe_history_source'))
        batch_op.drop_index(batch_op.f('ix_catch_recipe_history_recipe'))

    # ### end Alembic commands ###
