"""Add skin pack buy count

Revision ID: 23317670dced
Revises: 440565df3bc4
Create Date: 2025-01-22 12:58:02.804708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23317670dced"
down_revision: Union[str, None] = "440565df3bc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "buy_skin_box_count_in_this_week",
                sa.Integer(),
                server_default="0",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_user_data", schema=None) as batch_op:
        batch_op.drop_column("buy_skin_box_count_in_this_week")

    # ### end Alembic commands ###
