"""add recipe

Revision ID: 31d679f703f1
Revises: 393becfaaa91
Create Date: 2024-06-26 03:52:33.442072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31d679f703f1"
down_revision: Union[str, None] = "393becfaaa91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catch_recipe",
        sa.Column("award1", sa.Integer(), nullable=True),
        sa.Column("award2", sa.Integer(), nullable=True),
        sa.Column("award3", sa.Integer(), nullable=True),
        sa.Column("possibility", sa.Float(), nullable=False),
        sa.Column("result", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["award1"], ["catch_award.data_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["award2"], ["catch_award.data_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["award3"], ["catch_award.data_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["result"], ["catch_award.data_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("data_id"),
    )
    with op.batch_alter_table("catch_recipe", schema=None) as batch_op:
        batch_op.create_index(
            "catch_recipe_index", ["award1", "award2", "award3"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_catch_recipe_result"), ["result"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_recipe", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_recipe_result"))
        batch_op.drop_index("catch_recipe_index")

    op.drop_table("catch_recipe")
    # ### end Alembic commands ###
