"""modify class name

迁移 ID: 4572f9f0920f
父迁移: f236f1ac7e7b
创建时间: 2024-06-11 14:11:16.041526

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "4572f9f0920f"
down_revision: str | Sequence[str] | None = "f236f1ac7e7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_level", schema=None) as batch_op:
        # batch_op.add_column(sa.Column('color_code', sa.String(), nullable=False))
        # batch_op.drop_column('level_color_code')

        batch_op.alter_column("level_color_code", new_column_name="color_code")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_level", schema=None) as batch_op:
        # batch_op.add_column(sa.Column('level_color_code', sa.VARCHAR(), nullable=False))
        # batch_op.drop_column('color_code')

        batch_op.alter_column("color_code", new_column_name="level_color_code")

    # ### end Alembic commands ###
