"""fix catch group on delete

Revision ID: 898044c4292d
Revises: 0a40bf271d0c
Create Date: 2024-06-25 00:36:00.429779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "898044c4292d"
down_revision: Union[str, None] = "0a40bf271d0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_catch_award_catch_group_catch_catch_group_data_id", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_catch_award_catch_group_catch_catch_group_data_id",
            "catch_catch_group",
            ["catch_group"],
            ["data_id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_catch_award_catch_group_catch_catch_group_data_id", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_catch_award_catch_group_catch_catch_group_data_id",
            "catch_catch_group",
            ["catch_group"],
            ["data_id"],
        )

    # ### end Alembic commands ###
