"""fix

Revision ID: 9f390e2897d4
Revises: b926ffa19a6e
Create Date: 2024-06-15 22:41:05.361505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f390e2897d4"
down_revision: Union[str, None] = "b926ffa19a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_level", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_catch_level_name"), ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_level", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_catch_level_name"), type_="unique")

    # ### end Alembic commands ###
