"""add column for award

Revision ID: b640fb1cd2c1
Revises: 31d679f703f1
Create Date: 2024-07-02 23:16:35.177735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b640fb1cd2c1'
down_revision: Union[str, None] = '31d679f703f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_special_get_only', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.drop_column('is_special_get_only')

    # ### end Alembic commands ###
