"""add indexes

Revision ID: b926ffa19a6e
Revises: 89e550ebc005
Create Date: 2024-06-15 22:30:26.207854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b926ffa19a6e'
down_revision: Union[str, None] = '89e550ebc005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('catch_award', schema=None) as batch_op:
            batch_op.drop_constraint('uq_catch_award_name', type_='unique')
    except:
        pass

    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catch_award_name'), ['name'], unique=True)

    try:
        with op.batch_alter_table('catch_award_alt_name', schema=None) as batch_op:
            batch_op.drop_constraint('uq_catch_award_alt_name_name', type_='unique')
    except:
        pass

    with op.batch_alter_table('catch_award_alt_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catch_award_alt_name_award_id'), ['award_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_catch_award_alt_name_name'), ['name'], unique=True)

    try:
        with op.batch_alter_table('catch_level_alt_name', schema=None) as batch_op:
            batch_op.drop_constraint('uq_catch_level_alt_name_name', type_='unique')
    except:
        pass

    with op.batch_alter_table('catch_level_alt_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catch_level_alt_name_name'), ['name'], unique=True)

    try:
        with op.batch_alter_table('catch_skin_alt_name', schema=None) as batch_op:
            batch_op.drop_constraint('uq_catch_skin_alt_name_name', type_='unique')
    except:
        pass

    with op.batch_alter_table('catch_skin_alt_name', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catch_skin_alt_name_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_skin_alt_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catch_skin_alt_name_name'))
        batch_op.create_unique_constraint('uq_catch_skin_alt_name_name', ['name'])

    with op.batch_alter_table('catch_level_alt_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catch_level_alt_name_name'))
        batch_op.create_unique_constraint('uq_catch_level_alt_name_name', ['name'])

    with op.batch_alter_table('catch_award_alt_name', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catch_award_alt_name_name'))
        batch_op.drop_index(batch_op.f('ix_catch_award_alt_name_award_id'))
        batch_op.create_unique_constraint('uq_catch_award_alt_name_name', ['name'])

    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catch_award_name'))
        batch_op.create_unique_constraint('uq_catch_award_name', ['name'])

    # ### end Alembic commands ###
