"""change data type to string to avoid oor

迁移 ID: c77a72a0de61
父迁移: 3012889256de
创建时间: 2024-06-14 04:14:41.965538

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c77a72a0de61'
down_revision: str | Sequence[str] | None = '3012889256de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_user_data', schema=None) as batch_op:
        batch_op.alter_column('qq_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_user_data', schema=None) as batch_op:
        batch_op.alter_column('qq_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
