"""add index for awards

迁移 ID: cd4e2021645a
父迁移: 20fe0d856b29
创建时间: 2024-06-14 18:31:49.763763

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "cd4e2021645a"
down_revision: str | Sequence[str] | None = "20fe0d856b29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_award_level_id"), ["level_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_award_level_id"))

    # ### end Alembic commands ###
