"""on delete cascade

Revision ID: da03ef47a8c3
Revises: 9f390e2897d4
Create Date: 2024-06-16 02:48:00.918924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da03ef47a8c3'
down_revision: Union[str, None] = '9f390e2897d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_level_id_catch_level', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_level_id_catch_level', 'catch_level', ['level_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_award_alt_name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_alt_name_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_alt_name_award_id_catch_award', 'catch_award', ['award_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_award_counter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_counter_target_user_id_catch_user_data', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_award_counter_target_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_counter_target_user_id_catch_user_data', 'catch_user_data', ['target_user_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_award_counter_target_award_id_catch_award', 'catch_award', ['target_award_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_award_stats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_stats_target_award_id_catch_award', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_award_stats_target_user_id_catch_user_data', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_stats_target_user_id_catch_user_data', 'catch_user_data', ['target_user_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_award_stats_target_award_id_catch_award', 'catch_award', ['target_award_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_award_tag_relation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_tag_relation_tag_id_catch_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_award_tag_relation_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_tag_relation_award_id_catch_award', 'catch_award', ['award_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_award_tag_relation_tag_id_catch_tag', 'catch_tag', ['tag_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_level_alt_name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_level_alt_name_level_id_catch_level', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_level_alt_name_level_id_catch_level', 'catch_level', ['level_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_level_tag_relation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_level_tag_relation_tag_id_catch_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_level_tag_relation_level_id_catch_level', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_level_tag_relation_tag_id_catch_tag', 'catch_tag', ['tag_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_level_tag_relation_level_id_catch_level', 'catch_level', ['level_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_skin', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_applied_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_applied_award_id_catch_award', 'catch_award', ['applied_award_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_skin_alt_name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_alt_name_skin_id_catch_skin', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_alt_name_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_skin_own_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_own_record_skin_id_catch_skin', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_skin_own_record_user_id_catch_user_data', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_own_record_user_id_catch_user_data', 'catch_user_data', ['user_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_skin_own_record_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_skin_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_record_user_id_catch_user_data', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_skin_record_skin_id_catch_skin', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_record_user_id_catch_user_data', 'catch_user_data', ['user_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_skin_record_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'], ondelete='CASCADE')

    with op.batch_alter_table('catch_skin_tag_relation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_tag_relation_tag_id_catch_tag', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_skin_tag_relation_skin_id_catch_skin', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_tag_relation_tag_id_catch_tag', 'catch_tag', ['tag_id'], ['data_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_catch_skin_tag_relation_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_skin_tag_relation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_tag_relation_skin_id_catch_skin', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_skin_tag_relation_tag_id_catch_tag', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_tag_relation_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_skin_tag_relation_tag_id_catch_tag', 'catch_tag', ['tag_id'], ['data_id'])

    with op.batch_alter_table('catch_skin_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_record_skin_id_catch_skin', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_skin_record_user_id_catch_user_data', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_record_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_skin_record_user_id_catch_user_data', 'catch_user_data', ['user_id'], ['data_id'])

    with op.batch_alter_table('catch_skin_own_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_own_record_user_id_catch_user_data', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_skin_own_record_skin_id_catch_skin', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_own_record_user_id_catch_user_data', 'catch_user_data', ['user_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_skin_own_record_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'])

    with op.batch_alter_table('catch_skin_alt_name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_alt_name_skin_id_catch_skin', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_alt_name_skin_id_catch_skin', 'catch_skin', ['skin_id'], ['data_id'])

    with op.batch_alter_table('catch_skin', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_skin_applied_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_skin_applied_award_id_catch_award', 'catch_award', ['applied_award_id'], ['data_id'])

    with op.batch_alter_table('catch_level_tag_relation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_level_tag_relation_level_id_catch_level', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_level_tag_relation_tag_id_catch_tag', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_level_tag_relation_level_id_catch_level', 'catch_level', ['level_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_level_tag_relation_tag_id_catch_tag', 'catch_tag', ['tag_id'], ['data_id'])

    with op.batch_alter_table('catch_level_alt_name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_level_alt_name_level_id_catch_level', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_level_alt_name_level_id_catch_level', 'catch_level', ['level_id'], ['data_id'])

    with op.batch_alter_table('catch_award_tag_relation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_tag_relation_award_id_catch_award', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_award_tag_relation_tag_id_catch_tag', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_tag_relation_award_id_catch_award', 'catch_award', ['award_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_award_tag_relation_tag_id_catch_tag', 'catch_tag', ['tag_id'], ['data_id'])

    with op.batch_alter_table('catch_award_stats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_stats_target_user_id_catch_user_data', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_award_stats_target_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_stats_target_user_id_catch_user_data', 'catch_user_data', ['target_user_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_award_stats_target_award_id_catch_award', 'catch_award', ['target_award_id'], ['data_id'])

    with op.batch_alter_table('catch_award_counter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_counter_target_award_id_catch_award', type_='foreignkey')
        batch_op.drop_constraint('fk_catch_award_counter_target_user_id_catch_user_data', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_counter_target_award_id_catch_award', 'catch_award', ['target_award_id'], ['data_id'])
        batch_op.create_foreign_key('fk_catch_award_counter_target_user_id_catch_user_data', 'catch_user_data', ['target_user_id'], ['data_id'])

    with op.batch_alter_table('catch_award_alt_name', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_alt_name_award_id_catch_award', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_alt_name_award_id_catch_award', 'catch_award', ['award_id'], ['data_id'])

    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catch_award_level_id_catch_level', type_='foreignkey')
        batch_op.create_foreign_key('fk_catch_award_level_id_catch_level', 'catch_level', ['level_id'], ['data_id'])

    # ### end Alembic commands ###
