"""add tag system

迁移 ID: f213e4189814
父迁移: 7a3e2df14337
创建时间: 2024-06-12 00:37:13.639455

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f213e4189814"
down_revision: str | Sequence[str] | None = "7a3e2df14337"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catch_tag",
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.Column("tag_args", sa.String(), nullable=False),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("data_id", name=op.f("pk_catch_tag")),
        info={"bind_key": "catch"},
    )
    with op.batch_alter_table("catch_tag", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_tag_updated_at"), ["updated_at"], unique=False
        )

    op.create_table(
        "catch_level_tag_relation",
        sa.Column("level_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["catch_level.data_id"],
            name=op.f("fk_catch_level_tag_relation_level_id_catch_level"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["catch_tag.data_id"],
            name=op.f("fk_catch_level_tag_relation_tag_id_catch_tag"),
        ),
        sa.PrimaryKeyConstraint("data_id", name=op.f("pk_catch_level_tag_relation")),
        info={"bind_key": "catch"},
    )
    with op.batch_alter_table("catch_level_tag_relation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_level_tag_relation_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "catch_award_tag_relation",
        sa.Column("award_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["award_id"],
            ["catch_award.data_id"],
            name=op.f("fk_catch_award_tag_relation_award_id_catch_award"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["catch_tag.data_id"],
            name=op.f("fk_catch_award_tag_relation_tag_id_catch_tag"),
        ),
        sa.PrimaryKeyConstraint("data_id", name=op.f("pk_catch_award_tag_relation")),
        info={"bind_key": "catch"},
    )
    with op.batch_alter_table("catch_award_tag_relation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_award_tag_relation_updated_at"),
            ["updated_at"],
            unique=False,
        )

    op.create_table(
        "catch_skin_tag_relation",
        sa.Column("skin_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("data_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skin_id"],
            ["catch_skin.data_id"],
            name=op.f("fk_catch_skin_tag_relation_skin_id_catch_skin"),
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["catch_tag.data_id"],
            name=op.f("fk_catch_skin_tag_relation_tag_id_catch_tag"),
        ),
        sa.PrimaryKeyConstraint("data_id", name=op.f("pk_catch_skin_tag_relation")),
        info={"bind_key": "catch"},
    )
    with op.batch_alter_table("catch_skin_tag_relation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_catch_skin_tag_relation_updated_at"),
            ["updated_at"],
            unique=False,
        )

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.drop_column("tags")

    with op.batch_alter_table("catch_level", schema=None) as batch_op:
        batch_op.drop_column("tags")

    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.drop_column("tags")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_skin", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags", sa.VARCHAR(), server_default=sa.text("'0'"), nullable=False
            )
        )

    with op.batch_alter_table("catch_level", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags", sa.VARCHAR(), server_default=sa.text("'0'"), nullable=False
            )
        )

    with op.batch_alter_table("catch_award", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags", sa.VARCHAR(), server_default=sa.text("('')"), nullable=False
            )
        )

    with op.batch_alter_table("catch_skin_tag_relation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_skin_tag_relation_updated_at"))

    op.drop_table("catch_skin_tag_relation")
    with op.batch_alter_table("catch_award_tag_relation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_award_tag_relation_updated_at"))

    op.drop_table("catch_award_tag_relation")
    with op.batch_alter_table("catch_level_tag_relation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_level_tag_relation_updated_at"))

    op.drop_table("catch_level_tag_relation")
    with op.batch_alter_table("catch_tag", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_catch_tag_updated_at"))

    op.drop_table("catch_tag")
    # ### end Alembic commands ###
