"""add index to stats

迁移 ID: f3040b70c492
父迁移: c77a72a0de61
创建时间: 2024-06-14 17:33:25.049324

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f3040b70c492"
down_revision: str | Sequence[str] | None = "c77a72a0de61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award_counter", schema=None) as batch_op:
        batch_op.create_index(
            "storage_stat_index", ["target_user_id", "target_award_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("catch_award_counter", schema=None) as batch_op:
        batch_op.drop_index("storage_stat_index")

    # ### end Alembic commands ###
