"""fix name

迁移 ID: 7a3e2df14337
父迁移: 746ac4262a29
创建时间: 2024-06-11 23:08:04.471192

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7a3e2df14337'
down_revision: str | Sequence[str] | None = '746ac4262a29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('sorting_priority', sa.Integer(), nullable=False))
        # batch_op.drop_column('sortingPriority')
        batch_op.alter_column('sortingPriority', new_column_name='sorting_priority')

    with op.batch_alter_table('catch_level', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('sorting_priority', sa.Integer(), nullable=False))
        # batch_op.drop_column('sortingPriority')
        batch_op.alter_column('sortingPriority', new_column_name='sorting_priority')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_level', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('sortingPriority', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        # batch_op.drop_column('sorting_priority')
        batch_op.alter_column('sorting_priority', new_column_name='sortingPriority')

    with op.batch_alter_table('catch_award', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('sortingPriority', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        # batch_op.drop_column('sorting_priority')
        batch_op.alter_column('sorting_priority', new_column_name='sortingPriority')

    # ### end Alembic commands ###
