"""add shop

迁移 ID: 62920b0d0532
父迁移: 19d073c18106
创建时间: 2024-06-10 11:40:43.301939

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '62920b0d0532'
down_revision: str | Sequence[str] | None = '19d073c18106'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catch_award_stats',
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_award_id', sa.Integer(), nullable=True),
    sa.Column('award_count', sa.Integer(), nullable=False),
    sa.Column('data_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_award_id'], ['catch_award.data_id'], name=op.f('fk_catch_award_stats_target_award_id_catch_award')),
    sa.ForeignKeyConstraint(['target_user_id'], ['catch_user_data.data_id'], name=op.f('fk_catch_award_stats_target_user_id_catch_user_data')),
    sa.PrimaryKeyConstraint('data_id', name=op.f('pk_catch_award_stats')),
    info={'bind_key': 'passbotqwq'}
    )
    with op.batch_alter_table('catch_award_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catch_award_stats_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('catch_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default=str(0.0)))

    with op.batch_alter_table('catch_skin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default=str(-1.0)))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch_skin', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('catch_level', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('catch_award_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catch_award_stats_updated_at'))

    op.drop_table('catch_award_stats')
    # ### end Alembic commands ###
